#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 28
#SBATCH --time 00:10:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
# export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so
# mpirun -ppn 28 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpirun -ppn 28 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# mpirun -ppn 28 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
mpirun -np 28 -print-rank-map ./d2q9-bgk input_128x128.params obstacles_128x128.da
# srun --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
